% make sure the startup.m file does not exist or has just a dummy line

% ensure a vanilla path
restoredefaultpath;

% add RetinotopySkeleton to path
addpath(genpath('path/to/RetinotopySkeleton'));

% add analyzePRF version 1.2 to path
addpath(genpath('path/to/analyzePRF-1.2'));

% compile fitnonlinearmodel.m into an executable
mcc -a makegaussian2d.m ...        % extra functions in anonymous functions
  -a loadbinary.m ...
  -a subscript.m ...
  -a loadmulti.m ...
  -a conv2run.m ...
  -a posrect.m ...
  -a vflatten.m ...
  -a placematrix.m ...
  -a calccod.m ...
  -a analyzePRF_chpc.m ...
  -v -m -R -nojvm -R -nodisplay -R singleCompThread ...
  fitnonlinearmodel.m;

% compile RetinotopyAnalysis.m into an executable
mcc -v -m -R nojvm -R -nodisplay -R singleCompThread RetinotopyAnalysis.m;
